### ISSUE TITLE
json variables send to restapi can't deserialize

### ISSUE THREAD

**Issue by SmithXiong** [camunda/camunda-bpm-sdk-js#122]
I want send a json type variables,but it got error 
`
var variables = {data:{name:'smith',sex:0,age:18,hobby:['sing','read']}}
processDefinitionService.submitForm({
                id: processDefinitionId,
                businessKey: '1234',
                variables: {
                    formdata: {
                        value: JSON.stringify(variables).replace(/"/g,'\\"'),
                        type: 'json'
                    }
                }
            }`
it's success start a process,but i can't get the variables,it got error
/engine-rest/task/02ac0cef-9c74-11e9-bd72-0255ac1001b9/variables
response
{
    "type": "ProcessEngineException",
    "message": "Cannot deserialize object in variable 'formdata': SPIN/JACKSON-JSON-01001 Unable to parse input into json node"
}
what should i do?

**Comment by marstamm** [comment]
Hi,

as you have probably noticed we did not respond to github issues in quite some time. As we are migrating the sideprojects into our [main repository](https://github.com/camunda/camunda-bpm-webapp), we will close the issues here.

I recommend to have a look at [our community forum](https://forum.camunda.org/) and ask there if your question still stands.
