### ISSUE TITLE
Store only updated variables

### ISSUE THREAD

**Issue by danimasa** [camunda/camunda-bpm-sdk-js#125]
When I call the store function, all variables are stored but _I need only updated variables_.

In the current situation, if some variable is changed in some parallel form the current stored variable, even if it is not changed (and in most of my cases the values is only for visualization), is stored with the older value. And in submit function it takes preference over the current value from server.

In my point of view, only changed variables should be stored when I call the store function. The others should always be fetched from server.

**Comment by marstamm** [comment]
Hi,

as you have probably noticed we did not respond to github issues in quite some time. As we are migrating the sideprojects into our [main repository](https://github.com/camunda/camunda-bpm-webapp), we will close the issues here.

I created the ticket https://jira.camunda.com/browse/CAM-11201 to reflect you feature request. You can add comments and track its progress there.
