### ISSUE TITLE
Feature request: publish Typescript type definitions

### ISSUE THREAD

**Issue by emmanuel** [camunda/camunda-bpm-sdk-js#136]
It would ease use of this library in Typescript projects if there were type definitions published. It's clear that the types of many objects, arguments, etc. have been thought about (given the JSDoc comments); would be great to see those those type definitions formalized (e.g., as a `.d.ts`) so that they can be consumed directly in Typescript.

**Comment by marstamm** [comment]
Hi,

as you have probably noticed we did not respond to github issues in quite some time. As we are migrating the sideprojects into our [main repository](https://github.com/camunda/camunda-bpm-webapp), we will close the issues here.

I created the ticket https://jira.camunda.com/browse/CAM-11200 to reflect you feature request. You can add comments and track its progress there.
