### ISSUE TITLE
What about outputs?

### ISSUE THREAD

**Issue by leolux** [camunda/camunda-bpm-sdk-js#14]
Is there any way to output a camunda variable inside an embedded form besides input fields?
I found the file https://github.com/camunda/camunda-bpm-sdk-js/blob/master/doc/embedded-forms/controls/inputs.md. But what about outputs.md?

**Comment by SebastianStamm** [comment]
There is a more up to date version of the documentation available at https://docs.camunda.org

For your case, you could use a hidden input field to tell the sdk to fetch the variable and then use the generated angular binding in any other field within the form, see: https://docs.camunda.org/manual/7.5/reference/embedded-forms/controls/hidden/.

You could also use Javascript to fetch additional variables: https://docs.camunda.org/manual/7.5/reference/embedded-forms/javascript/lifecycle/#fetching-additional-variables

Does this help you?

**Comment by meyerdan** [comment]
https://app.camunda.com/jira/browse/CAM-6187

**Comment by leolux** [comment]
I haven't found a way to output variables yet. As far as I understood the documentation the directive 'cam-variable-name' seems to focus only on input elements including hidden inputs. At the moment there is no example of how to output values without using input elements.

As I don't fully understand the way the directive works under the hood I tried to access the process variable 'email' in the rootScope without success:
- {{email}}
- <span cam-variable-name="email"></span>

Both attempts didn't work. Maybe there is another way of handling camunda triggered broadcast events or anything that AngularJs brings with it.  What do you think?

Another attempt was to access the AngularJS Dependency Graph [1] for inspecting the scope. But I couldn't manage to figure out the app name in first place.

[1] https://chrome.google.com/webstore/detail/angularjs-graph

**Comment by SebastianStamm** [comment]
If you replace your span element with an `<input type="hidden">` element, you should be able to access the variable value using `{{email}}` Since the input is hidden, the input is not visible in the form itself, but the variable value will be bound to the angular scope.

If you do not want to use a hidden input field, you have to use Javascript to fetch the variable.

**Comment by leolux** [comment]
Now I got it. The variable has to be fetched by an `<input type="hidden">` or by an visible input element or by Javascript using the camForm variable. And the output works only inside the `<form>` element and not above where I placed the headline.

Thank you!
