### ISSUE TITLE
CORSE blocks XHR for the protocol scheme http

### ISSUE THREAD

**Issue by leolux** [camunda/camunda-bpm-sdk-js#15]
I noticed the following error in the JS console while debugging a embedded task form:
`camunda-bpm-sdk-angular.js:7471 XMLHttpRequest cannot load app:forms/validate-order.html?noCache=1465802773984. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.f.end @ camunda-bpm-sdk-angular.js:7471
XHR finished loading: GET "http://localhost:8090/camunda/api/engine/engine/default/task/1ddc76ff-30aa-11e6-b43f-c03896721ccf".`

Of course HTTPS would solve this issue. But during development I try to avoid TLS as long as I don't have a need for it (YAGNI principle). The question is: Does this error lead to any problems, side effects or inconsistent state? If yes it should be strongly recommended to setup SSL/TLS also for development.

**Comment by SebastianStamm** [comment]
This error is most likely not related to the camunda-bpm-sdk-js project, but with your integration of Camunda BPM. Usually, this error message is caused by not having the correct context path for your process application. Make sure that a GET request to the `/task/{id}/form` REST endpoint returns the correct context path: https://docs.camunda.org/manual/7.5/reference/rest/task/get-form-key/

**Comment by leolux** [comment]
Does the application camunda tasklist require the REST API?

As I do not need the REST API at the moment I removed the folder "engine-rest" from the tomcat webapps folder. After that the XHR error has dissapeared. So it seems to me that camunda tasklist works also without the REST API. But maybe I am totally wrong here. How is this possible?

**Comment by SebastianStamm** [comment]
Yes, Camunda Tasklist communicates with the engine via the REST-API. You can see that if you open the Developer console of your browser (F12) and take a look at the network tab. You can read more about the REST API here: https://docs.camunda.org/manual/latest/reference/rest/overview/

I do not know why removing the engine-rest directory from the tomcat webapp solves this issue for you, but it looks like the error is related to the Camunda integration and not with the camunda-bpm-sdk-js. Does this resolve your issue? You can also open a thread in the Camunda forum: https://forum.camunda.org/

**Comment by leolux** [comment]
Yes, removing the engine-rest directory effectively solves this issue. There are no more issues in the Network tab and or in the console. Instead there XHR requests to the REST API are still happening but without errors.

I had another look into the webapps directory of the pre-packaged Tomcat distribution from https://camunda.org/download/. The REST API implementation is contained twice in the webapps directory as the following screenshot shows:
![engine-rest-duplicate](https://cloud.githubusercontent.com/assets/5385814/16036415/15f147bc-321c-11e6-8e66-84ccb717022d.png)
The classes contained in camunda-engine-rest-7.4.0-classes are also present in the directory "engine-rest\WEB-INF\classes". 

The API duplication explains why the app camunda tasklist continues working after removing the directory "engine-rest" from tomcat. But it does not explain the issue itself. As you said it has probably something todo with the context path for the process application.

As we agree that the error is not related to the camunda-bpm-sdk-js project we can close the issue here. Suggestions and ideas how to keep track of this are welcome.
