### ISSUE TITLE
Process instance resource lacks of get method

### ISSUE THREAD

**Issue by alvarp** [camunda/camunda-bpm-sdk-js#16]
I've noticed that the process-instance resource doesn't have any get method. Is there any reason for that? The process-definition has one and the [API documentation](https://docs.camunda.org/manual/7.5/reference/rest/process-instance/get/) has it too. 

The implementation should be as easy as copying the get method of process-definition.

**Comment by SebastianStamm** [comment]
There is no reason that I can think of other than "we didn't need it in the Camunda BPM Webapp yet".

If you want to, you can create a pull request with the implementation.

**Comment by alvarp** [comment]
I've noticed too that the submitForm method in the process-definition resource lacks of support of submit the form using a key AND a tenant-id.

In the next days I will send the pull request in order to solve both issues!

**Comment by SebastianStamm** [comment]
Cool :) Thanks for taking the time.

I suggest we discuss the proposed changes in the pull requests themselves, so I am closing this issue. Feel free to reopen it, if you think it requires further discussion.
