### ISSUE TITLE
Using SDK for full process execution

### ISSUE THREAD

**Issue by huksley** [camunda/camunda-bpm-sdk-js#20]
Is it possible to use API for full process automation, beyond form implementation?

I.e.
- Auth
- Create instance
- Claim tasks
- Complete tasks

If it is possible, please provide documentation.
I am trying to create SPA with custom interface and using Camunda BPM only via REST API.

**Comment by SebastianStamm** [comment]
The SDK provides an abstraction layer for the REST API of Camunda. In the [lib/api-client/resources](https://github.com/camunda/camunda-bpm-sdk-js/tree/master/lib/api-client/resources) directory you will find files that correspond with the Resources of the [REST API](https://docs.camunda.org/manual/7.5/reference/rest/). For example, if you want to claim a task, you would get the task resource via `camClient.resource('task')` and call the [claim method](https://github.com/camunda/camunda-bpm-sdk-js/blob/master/lib/api-client/resources/task.js#L340-L355).

There might be methods missing that are provided by the REST API but are not included in the camunda-bpm-sdk-js. If you need those, feel free to provide a pull request :)

**Comment by huksley** [comment]
Is there any documentation or I can generate it myself?

**Comment by zeropaper** [comment]
Hi @huksley ,

We got rid of JSDoc because we had some issues with it in our build (and anyways, it's difficult to set it up correctly).

I gave a quick try at ESDoc but it's meant for ES 2015 only.

So for now, I think that you will have to look at the source (which is fairly documented).

Cheers
