### ISSUE TITLE
NPM module not available for this repo. Any reason?

### ISSUE THREAD

**Issue by rusiarohit** [camunda/camunda-bpm-sdk-js#21]
Hi, 

I wanted to utilize the NPM module of this repo as I am using the Camunda REST api from my node application but I couldn't find the NPM module for this. Can you please make it available?

**Comment by zeropaper** [comment]
You could also easily install it (and add it to your package.json) with the following command:
```sh
npm i --save-dev camunda/camunda-bpm-sdk-js
```

**Comment by rusiarohit** [comment]
Thank you! I was trying npm i --save-dev camunda-bpm-sdk-js before and it didn't work.

**Comment by zeropaper** [comment]
yeah.. it's a subtility from NPM, you can install any GH repos (which has a package.json at its root) using

```sh
npm i <gh-orga-name/gh-user-name>/<gh-repo-name>
```
