### ISSUE TITLE
REST endpoint response vs camunda-bpm-sdk-js method response defers

### ISSUE THREAD

**Issue by rusiarohit** [camunda/camunda-bpm-sdk-js#22]
Hi,

This is not a issue more of a enquiry. I am using Camunda SDK to fetch list of tasks when I try the direct rest endpoint I get an array of tasks but if I use SDK I get the response something like below. 

{
_link: ...
_embedded: {
assignee:[],
processDefinition:[],
tasks:[]
}
count:4
}
Also processDefinition is embedded inside each task which I don't need. Is there any configuration I can change to get the exact same response as it comes from REST endpoint?

**Comment by zeropaper** [comment]
Not sure to understand what you want or which method you use. Can you elaborate a bit please?

On a side note, we use [HAL](http://stateless.co/hal_specification.html) to reduce the amount of needed requests on some endpoints (and this is **awesome** :) for front-end/js so it's very unlikely going to vanish).

**Comment by rusiarohit** [comment]
Sorry to create confusion what I mean't was. I am working on a Node.js application
I can get list of tasks by 2 ways using 

1 : REST API
https://docs.camunda.org/manual/7.3/api-references/rest/#task-get-tasks

2: camunda-bpm-sdk-js (which in-turn uses REST APIs, I checked the source it does use REST API)
`var camundaClient = _initializeClient(camundaConfig.apiUri, camundaConfig.authType, camundaConfig.userName, camundaConfig.password);
var taskService = new camundaClient.resource('task');
taskService.list({}, function (err, result) {
		callback(err, result);
});`

Now, when I use REST API in POSTMAN or any REST client I get response task list as a plain array but when I use the camunda-bpm-sdk-js which I am using heavily in my application I get the response in 
 HAL format (I am new to this). I understand it is good to do it in certain cases as it gives you assignee and process definition details embedded but I don't want them so can you suggest if there is a way around to get it as plain JSON not HAL? Hope its clear now.

**Comment by zeropaper** [comment]
It is a bit clearer.
The SDK prefers "application/hal+json" (in the "Accept" header, postman does not send that header by default ;) ).
If you set the "Accept" header, this will not happen:
https://github.com/camunda/camunda-bpm-sdk-js/blob/master/lib/api-client/index.js#L23
https://github.com/camunda/camunda-bpm-sdk-js/blob/master/lib/api-client/http-client.js#L25-L27

**Comment by rusiarohit** [comment]
But I want application/json in SDK.. if I try to set it explicitly in
client it doesn't work. Does SDK support non hal+json?

**Comment by zeropaper** [comment]
If you instantiate the client with the right configuration, yes.
```js
var jsonApiClient = new CamundaClient({
  // ... rest of the configuration
  headers: {
    Accept: 'application/json'
  }
});
```

**Comment by rusiarohit** [comment]
Yes , I tried that. Below is my code and error log.

```
return new camundaAPI.Client({
			apiUri: apiUri,
			headers: {Authorization: 'Basic ' + base64Token,Accept:'application/json'}

		});
```

```

/Users/rusiarohit/Desktop/workspace/projects/testapp/code/testapp/node_modules/camunda-bpm-sdk-js/lib/api-client/resources/task.js:112
      var tasks = data._embedded.task || data._embedded.tasks;
                                ^

TypeError: Cannot read property 'task' of undefined
    at http.get.done (/Users/rusiarohit/Desktop/workspace/projects/testapp/code/testapp/node_modules/camunda-bpm-sdk-js/lib/api-client/resources/task.js:112:33)
    at /Users/rusiarohit/Desktop/workspace/projects/testapp/code/testapp/node_modules/camunda-bpm-sdk-js/lib/api-client/http-client.js:68:5
    at Request.callback (/Users/rusiarohit/Desktop/workspace/projects/testapp/code/testapp/node_modules/camunda-bpm-sdk-js/node_modules/superagent/lib/node/index.js:785:12)
    at IncomingMessage.<anonymous> (/Users/rusiarohit/Desktop/workspace/projects/testapp/code/testapp/node_modules/camunda-bpm-sdk-js/node_modules/superagent/lib/node/index.js:990:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by zeropaper** [comment]
OK. There's a bug here. I openned a ticket in our Jira
https://app.camunda.com/jira/browse/CAM-7055
(the fix is coming soon)

**Comment by rusiarohit** [comment]
Thanks!
