### ISSUE TITLE
AngularJS is loaded twice in client setup

### ISSUE THREAD

**Issue by bentrm** [camunda/camunda-bpm-sdk-js#23]
I'm building a small app using CamSDK as a module imported via:

````
import angular from 'angular';
import CamSDK from 'camunda-bpm-sdk-js/lib/angularjs/index.js';

angular
    .module('app', ['cam.embedded.forms'])
    .constant('CamSDK', CamSDK)
    ...
````

Unfortunately, this leads to angular being called twice during application startup. 

````
WARNING: Tried to load angular more than once.
````

It also bloats the app build via Webpack as the angular source code is included twice (this can be mitigated for production via dedup but loading angular twice still is a problem).

As a test I commented out [the line that requires angular](https://github.com/camunda/camunda-bpm-sdk-js/blob/master/lib/angularjs/forms/camunda-form-angular.js#L6) trusting that the `angular` object would be available as a peerDependency and all works nicely.

To make better use of the angular components, I would suggest to add `angular` as a peerDependency instead of an optionalDependency and use it as a global object. Also, it may make sense to migrate Angular-related stuff into a separate package? This would also allow to set the correct `main` option to load the angular component. Right now, this needs to be adjusted in the import path (see above) or via overriding the `package.json/main` key via the module loader/builder of your choice.

Edit: I just noticed that Angular 1.2.29 is loaded as an optionalDependency and installed in the packages `node_modules` folder. I assume this is the second instance of angular that is loaded in parallel to my peer dependency of 1.5.9.

**Comment by SebastianStamm** [comment]
As camunda-bpm-sdk-js is used in the Camunda webapp, we need the 1.2.29 version as some features in the webapp break with newer angular versions (though fixing that and upgrading angular to a newer version is something I want to do).

So if you want to have only one instance of angular, you would need to use the version that is provided by the SDK like this:

```
import angular from 'camunda-bpm-sdk-js/vendor/angular';
import CamSDK from 'camunda-bpm-sdk-js/lib/angularjs/index.js';
```

Would that be an option for you?
