### ISSUE TITLE
Vulnerabilities - Snyk wizard

### ISSUE THREAD

**Issue by harigopalakrishna** [camunda/camunda-bpm-sdk-js#25]
We ran Snyk Wizard on our project and found following vulnerabilities. Could you please address them?

---
✗ Low severity vulnerability found on angular@1.2.29
- desc: Arbitrary Code Execution
- info: https://snyk.io/vuln/npm:angular:20140608
- from: project@0.3.3 > camunda-bpm-sdk-js@7.7.0-SNAPSHOT > angular@1.2.29
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ Medium severity vulnerability found on angular@1.2.29
- desc: Cross-site Scripting (XSS)
- info: https://snyk.io/vuln/npm:angular:20140908
- from: project@0.3.3 > camunda-bpm-sdk-js@7.7.0-SNAPSHOT > angular@1.2.29
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ Medium severity vulnerability found on angular@1.2.29
- desc: Arbitrary Command Execution
- info: https://snyk.io/vuln/npm:angular:20141104
- from: project@0.3.3 > camunda-bpm-sdk-js@7.7.0-SNAPSHOT > angular@1.2.29
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ High severity vulnerability found on angular@1.2.29
- desc: Arbitrary Code Execution
- info: https://snyk.io/vuln/npm:angular:20150310
- from: project@0.3.3 > camunda-bpm-sdk-js@7.7.0-SNAPSHOT > angular@1.2.29
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ High severity vulnerability found on angular@1.2.29
- desc: Cross-site Scripting (XSS)
- info: https://snyk.io/vuln/npm:angular:20150807
- from: project@0.3.3 > camunda-bpm-sdk-js@7.7.0-SNAPSHOT > angular@1.2.29
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ High severity vulnerability found on angular@1.2.29
- desc: Cross-site Scripting (XSS)
- info: https://snyk.io/vuln/npm:angular:20150909
- from: project@0.3.3 > camunda-bpm-sdk-js@7.7.0-SNAPSHOT > angular@1.2.29
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ Medium severity vulnerability found on angular@1.2.29
- desc: Cross-site Scripting (XSS)
- info: https://snyk.io/vuln/npm:angular:20151130
- from: project@0.3.3 > camunda-bpm-sdk-js@7.7.0-SNAPSHOT > angular@1.2.29
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ Medium severity vulnerability found on angular@1.2.29
- desc: Cross-site Scripting (XSS)
- info: https://snyk.io/vuln/npm:angular:20151205
- from: project@0.3.3 > camunda-bpm-sdk-js@7.7.0-SNAPSHOT > angular@1.2.29
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ Medium severity vulnerability found on angular@1.2.29
- desc: Arbitrary Script Injection
- info: https://snyk.io/vuln/npm:angular:20160527
- from: project@0.3.3 > camunda-bpm-sdk-js@7.7.0-SNAPSHOT > angular@1.2.29
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.
---

**Comment by meyerdan** [comment]
Hi harigopalakrishna,

thanks for reporting this. The things you report seem to be related to the angular js dependency.
I am not falimiar with the "snyk" tool. It says that "No direct dependency upgrade can address this issue."
based on this I do not see what can be done. I am closing the issue.
If you know how to address these things we would be very happy to accept contributions. In that case just  reopen!

Best,
Daniel

**Comment by harigopalakrishna** [comment]
Hi Daniel - Thanks for your response.  Sorry for not being clear on the initial post.

"No direct dependency upgrade can address this issue" - is the feedback the security tool gave for my project. Upon digging deeper it appears that camunda bpm sdk is using older angular (<1.3.0) library, by upgrading camunda to use angular to version 1.3.0 or higher this vulnerability can be addressed. Makes sense?

Thanks,
Hari

**Comment by meyerdan** [comment]
Hi Hari,

thanks a lot for providing this feedback. If you are using only the SDK than it would be worth a try to override the angluar dependency in your project to (> 1.3.0.) and try out whether it works with that.

We use the SDK embedded in out webapp which means that we have camunda/camunda-commons-ui and camunda/camunda-bpm-webapp depending on that. Updating to angular 1.3.0 may be a "bigger project", I do not know.

I have created an issue for the larger project here: https://app.camunda.com/jira/browse/CAM-7397

**Comment by harigopalakrishna** [comment]
Got it, thanks Daniel!
