### ISSUE TITLE
Publish package to NPM

### ISSUE THREAD

**Issue by phairoh** [camunda/camunda-bpm-sdk-js#28]
There is a previously closed issue regarding this (#21) however I am not satisfied with using `npm i -d camunda/camunda-bpm-sdk-js` as it does not allow for any versioning of the dependency. Yes, I could indicate a specific commit but that is approximately 1 million times more annoying to maintain.

Is there a reason why this is not published on NPM?

**Comment by hawky-4s-** [comment]
@SebastianStamm : ping

**Comment by SebastianStamm** [comment]
I can't think of a reason to not publish it on NPM. After all, we are also publishing it on bower. There is an open JIRA ticket to publish the webapp and commons-ui projects on npm: https://app.camunda.com/jira/browse/CAM-7132

I added a comment to also get this repo on npm while we are on it.

**Comment by phairoh** [comment]
@SebastianStamm Thanks for the swift response. Given that the JIRA ticket is about 4 months old are you aware of an ETA? My team is implementing a solution with camunda right now and it would be helpful if this could be completed in the next month or 2.

**Comment by SebastianStamm** [comment]
@phairoh As far as I know this feature is currently not on the roadmap. The effort to make the libraries available via npm is very high and we currently don't have the capacity to do that.

**Comment by phairoh** [comment]
@SebastianStamm Thanks again for the quick response and for your candor. We will have to come up with another solution in the meantime.
