### ISSUE TITLE
Are the type utilities working with the new 7.8 camunda date format?

### ISSUE THREAD

**Issue by rmoskal** [camunda/camunda-bpm-sdk-js#31]
It seems like no, in the master branch.

This is the new format coming back for the REST API:

    yyyy-MM-dd['T'HH:mm[:ss[.SSS[Z]]]]

For example:  2018-05-02T15:03:16.753-0400

See https://docs.camunda.org/manual/7.8/reference/rest/overview/date-format/

It doesn't look to me like this being handled correctly. I have a fix. If you aren't planning to address this, let me know and I'll make a PR.

**Comment by marstamm** [comment]
Hi,

as you have probably noticed we did not respond to github issues in quite some time. As we are migrating the sideprojects into our [main repository](https://github.com/camunda/camunda-bpm-webapp), we will close the issues here.

We use momentJS to parse the values from the backend in our own webapps and do not plan to add parsing to the sdk-js at the current time.

I recommend to have a look at [our community forum](https://forum.camunda.org/) and ask there if your question still stands.
