### ISSUE TITLE
bower grunt to Webpack babel and yarn

### ISSUE THREAD

**Issue by ChuckIrvine** [camunda/camunda-bpm-sdk-js#34]
I think, for the most part, Webpack, babel and yarn are now preferred over bower and grunt. Would be great if camunda-bpm-sdk-js could be switched over to using those.

**Comment by marstamm** [comment]
Hi,

as you have probably noticed we did not respond to github issues in quite some time. As we are migrating the sideprojects into our [main repository](https://github.com/camunda/camunda-bpm-webapp), we will close the issues here.

I agree with you, but as this is a part of a larger project with a more complex build structure, this might not be tackled anytime soon.
Nevertheless, I created the ticket https://jira.camunda.com/browse/CAM-11202 to reflect you feature request. You can add comments and track its progress there.
