### ISSUE TITLE
Unable to initiate process instance with a start form

### ISSUE THREAD

**Issue by uf-kelvin-low** [camunda/camunda-bpm-sdk-js#35]
I am using "camunda-invoice" as example to initiate a process instance using Form SDK. With the guildeline from Camunda Docs, I am able to render the start form. But however, when I do a submission, the REST API (http://localhost:8080/engine-rest/engine/default/process-definition/.../submit-form) returns me HTTP Status 500. 

I am tried to troubleshoot, and I noticed that one of variable - "invoiceCategory" (which is the variable to hold the selected option on HTML Select element) is submitted as null. The root cause to this is the "getValue" function in "lib/forms/controls/choices-field-handler.js"

At least the following solution work at my end, but just to confirm should we rectify this `value = this.element.find('option:selected').attr('value');//.val();` statement to `value = this.element.find('option:selected').val();`?

**Comment by marstamm** [comment]
Hi,

as you have probably noticed we did not respond to github issues in quite some time. As we are migrating the sideprojects into our [main repository](https://github.com/camunda/camunda-bpm-webapp), we will close the issues here.

I recommend to have a look at [our community forum](https://forum.camunda.org/) and ask there if your question still stands.

From the commit history, this seems like a conscious decision at one point. If this is still a problem, please bump it in the forum and we will investigate further
