### ISSUE TITLE
Example of superagent-mock-config.js

### ISSUE THREAD

**Issue by vermauv** [camunda/camunda-bpm-sdk-js#36]
I didn't find any documentation for the tests provided, would be helpful how to call the get/post function available in exports of this file. The test under **test/client/coreSpec.js** just initializes and unsets it.

**Comment by marstamm** [comment]
Hi,

as you have probably noticed we did not respond to github issues in quite some time. As we are migrating the sideprojects into our [main repository](https://github.com/camunda/camunda-bpm-webapp), we will close the issues here.

I recommend to have a look at [our community forum](https://forum.camunda.org/) and ask there if your question still stands.
