### ISSUE TITLE
Get users profile sends HTTP DELETE

### ISSUE THREAD

**Issue by rkorn86** [camunda/camunda-bpm-sdk-js#7]
Are you sure, that https://github.com/camunda/camunda-bpm-sdk-js/blob/master/lib/api-client/resources/user.js#L138 should send "HTTP DELETE"? In the docs "HTTP GET" is mentioned for getting user profile, which makes much more sense.

**Comment by SebastianStamm** [comment]
You are most definitely right! Thanks for reporting
