### ISSUE TITLE
What is the intended behavior of returns for HttpClient?

### ISSUE THREAD

**Issue by lightswitch05** [camunda/camunda-bpm-sdk-js#9]
Many calls to `HttpClient` is returned (62 from a rough count), a few examples:

```JavaScript
Task.get = function(taskId, done) {
  return this.http.get(this.path +'/'+ taskId, {
    done: done
  });
};

/// ... 

Task.form = function(taskId, done) {
  return this.http.get(this.path +'/'+ taskId + '/form', {
    done: done
  });
};
```

However, HttpClient doesn't return anything for these methods:

```JavaScript
HttpClient.prototype.put = function(path, options) {
  // ...
  req.end(end(self, done));
};

//  Called by get: HttpClient.prototype.get
HttpClient.prototype.load = function(url, options) {
  // ...
  req.end(end(self, done));
}

HttpClient.prototype.del = function(path, options) {
  // ...
  req.end(end(self, done));
}

HttpClient.prototype.options = function(path, options) {
  // ...
  req.end(end(self, done));
};

// Post does have a return in case of an error
HttpClient.prototype.post = function(path, options) {
  // ...
  else if (!!options.fields || !!options.attachments) {
    return done(new Error('Multipart request is only supported in node.js environement.'));
  }
  req.end(end(self, done));
};
```

Rough count of undefined returns:

- `return this.http.get`: 22
- `return this.http.post`: 27 - these do have a return in case of an error
- `return this.http.put`: 7
- `return this.http.del`: 4
- `return this.http.options`: 2

When I originally noticed these calls had returns, I was excited and thought I could implement my callbacks using promises, but was disappointed the find the returns are alway undefined. What is the intended functionality here?

**Comment by zeropaper** [comment]
That's an interesting question who will be investigated.
Thanks for pointing it.

**Comment by zeropaper** [comment]
We opened a CAM issue for that: https://app.camunda.com/jira/browse/CAM-4811

**Comment by lightswitch05** [comment]
So there is no plans on adding support for promises? With all the `returns` already in place, seems like it would be trivial to start returning promises in the various `get`, `put`, `post` calls in `HttpClient`

**Comment by zeropaper** [comment]
We never discussed it internally, but feel free to send us a PR.

**Comment by meyerdan** [comment]
We should keep all options open to implement promises
