### ISSUE TITLE
npm audit returns 30 vulnerabilities for 7.10.0-SNAPSHOT

### ISSUE THREAD

**Issue by jeson114** [camunda/camunda-bpm-sdk-js#96]
The default npm package has even more vulnerabilities so i switched to package which was using a more recent release . Even with that newer package i am getting around 30 issues in the audit

**Comment by tasso94** [comment]
Hi Jeson,

do you face this problem still with the current Camunda BPM 7.12.0-SNAPSHOT?

We update the third-party dependencies regularly to mitigate the risk of vulnerabilities.

Please let me know if this is still an issue for you.

Cheers,
Tassilo
